### PR TITLE
Offer ability to update instead of creating a new checkRun

### LINKED ISSUE #40: JUnit report sent to wrong build
Dear maintainer,

Thanks so much for creating this excellent plugin and sharing it for others to use!

I have multiple workflows defined, and it seems that the check is added to the first workflow, rather than the one that actually ran the test suite. Is there some way to associate the report with the correct workflow definition? Ideally I'd like the report to be below the test suite (e.g. job that runs tests, publishes report, should have the report appended as a check below it or nearby)

### PR DESCRIPTION
**Pull request by mikepenz**
- update current run instead of creating a new one
   - FIX https://github.com/mikepenz/action-junit-report/issues/40

### CODE REVIEW

File: src/main.ts [hunk 1]
```diff
@@ -54,34 +55,70 @@ export async function run(): Promise<void> {
...
+          filter: 'latest'
+        })
+
+        core.debug(JSON.stringify(checks, null, 2))
+
+        const check_run_id = checks.data.check_runs[0].id
+
+        core.info(`ℹ️ Updating checks ${testResult.annotations.length}`)
+        for (let i = 0; i < testResult.annotations.length; i = i + 50) {
+          const sliced = testResult.annotations.slice(i, i + 50)
```
Comment (pbrisbin) [inline src/main.ts:86]: :ok_hand:
